version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "KexyBiscuit"
    commit-message:
      prefix: "workflows"
      include: "scope"
    labels:
      - "workflow"
    reviewers:
      - "KexyBiscuit"
      - "outloudvi"

  - package-ecosystem: "docker"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    assignees:
      - "KexyBiscuit"
    commit-message:
      prefix: "workflows"
      include: "scope"
    labels:
      - "workflow"
    reviewers:
      - "KexyBiscuit"
