name: Bug Report
description: Any other issues please report with this template
body:
- type: textarea
  attributes:
    label: Bug description
    description: A concise description of the issue
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the issue
  validations:
    required: true
- type: input
  attributes:
    label: Update channel(s)
    description: Update channel you are using
  validations:
    required: true
- type: textarea
  attributes:
    label: Package and version
    description: Execute `dpkg -s $PKG` and paste output below, where `$PKG` is the affected package. If uncertain, leave this section blank.
    render: bash
  validations:
    required: false
