name: FTBFS Report
description: Any FTBFS (Failed To Build From Source) issue should be filed with this template.
labels: ['FTBFS']
body:
- type: input
  attributes:
    label: 'Intended Version'
    description: 'What version update, revision were you trying to build?'
  validations:
    required: true
- type: input
  attributes:
    label: 'Target Branch'
    description: 'Which branch are you building for?'
  validations:
    required: true
- type: textarea
  attributes:
    label: 'Description'
    description: 'Please describe your issues when building the said package'
    placeholder: |
      Attach your build log, configuration changes, etc. here.
      If package only fails to build for a particular architecture, please specify.
  validations:
    required: true
