# This is the draft of security vulnerabilities bug report, next version, revision 4.1
name: 'Security Vulnerabilities Report'
description: 'Any security vulnerabilities report should be filed with this template.'
labels: ['security']
body:
# Field "Affected packages" is new in this draft and is designed for listing affected package(s) and component(s).
# E.g.: libX11 in `x11-lib`
# Note: 'version' is meant to remind the reporter to check whether the reporting CVE is applicable to current version.
- type: input
  attributes:
    label: 'Affected package (and version)'
    description: |
      Example: libX11 in `x11-lib` (7.7.20220817-1)
    placeholder: '`package_name` version'
  validations:
    required: true
- type: input
  attributes:
    label: 'CVE ID(s)'
    description: 'Fill N/A if no CVE ID is assigned.'
    placeholder: 'CVE-20xx-xxxx[, CVE-20xx-xxxx, ...]'
  validations:
    required: true
# Severity is a new field of the template. This may help maintainers to identify which issue is most urgent and require attentions.
- type: dropdown
  attributes:
    label: 'Severity'
    description: |
      Select the severity of reported vulnerability(ies). Choose the highest severity out of reported vulnerabilities. For details about different severity level, you may refer to [SUSE's security flaws rating](https://www.suse.com/support/security/rating/).
      Additionally, `0-day` is used to indicate that the reporting vulnerabilities is potentially being exploited for malicious activities. This is the highest severity rating regardless of its original severity.
    options:
      - '0-day'
      - 'Critical'
      - 'High'
      - 'Moderate'
      - 'Low'
  validations:
    required: true
- type: textarea
  attributes:
    label: 'Other security advisory ID(s）'
    description: 'Other security advisory(ies), mailing list message(s) or bug report(s). Please list with reference(s) to each ID.'
    placeholder: |
      Examples:
      - Debian: [DSA-xxxx-x](link_to_DSA)
      - Mail list: (link_to_mail_list_archive)
      - Bug report: (link_to_upstream_bug_report)
  validations:
    required: true
- type: textarea
  attributes:
    label: 'Description/References'
    description: |
      List of links to references, PoCs, etc., or other description may be listed here.
      You may also include supplemental details:
      - Version where the bug was introduced.
      - Possible security impact on AOSC OS.
      - Available PoCs (required if the reporting target is an AOSC-developed component).
      - Reasons to flag selected severity.
      - CWE (Common Weakness Enumeration), if applicable.
      - ...
  validations:
    required: true
# The original `patches` is renamed to `Fixed version or patches`. If an package update is suggested the reporter should include the latest version and the earliest fixed version if applicable.
- type: textarea
  attributes:
    label: 'Patch(es)/Solution(s)'
    description: |
      Enter N/A to indicate that a regular upgrade to latest version is favored. Otherwise, fill this field with one or more of the following:
      - Patch(es), if a backport is advised, or no new upstream release is available.
      - A specific non-latest version, if upgrading to latest may cause issue (please specify).
      - Other suggestions, such as a workaround/Errata documentation, if no fix is yet available.
    placeholder: |
      Example(s):
      - N/A
      - Apply patch: (link to patch)
      - Temporary disable the-buggy-feature-like-JNDI-on-log4j2
  validations:
    required: true

# Removed PoC(s) as it should be considered as a part of issue description
