name: Build packages on request

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  get-packages:
    if: ${{(github.event.comment.body == '/build' && github.event.issue.pull_request) || startsWith(github.event.comment.body, '/build ')}}
    runs-on: ubuntu-latest

    steps:
      - name: Add reaction to invocation comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{github.event.comment.id}}
          reactions: rocket

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        id: create-comment
        with:
          issue-number: ${{github.event.issue.number}}
          body: |
            🥰 Packages are building at ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.

      - uses: actions/checkout@v2
        if: ${{github.event.comment.body == '/build'}}

      - name: Checkout pull request
        if: ${{github.event.comment.body == '/build'}}
        env:
          PR_NUMBER: ${{github.event.issue.number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr checkout $PR_NUMBER

      - name: Get packages to build from repository
        uses: actions/github-script@v5
        id: get-packages-from-repo
        if: ${{github.event.comment.body == '/build'}}
        with:
          script: |
            let args = "";
            const options = {};
            options.listeners = {
              stdout: (data) => {
                args += data.toString();
              }
            };

            await exec.exec('git', ['diff', '--name-only', 'stable', 'HEAD', '*/spec'], options);
            const regex = /.*\/(.*)\/.*/gm;
            const packages = args.split('\n').map(arg => regex.exec(arg)).filter(arg => Array.isArray(arg)).map(arg => arg[1]);
            if (!Array.isArray(packages) || packages.length == 0) throw "No packages to build in the repository!";
            return packages;

      - name: Get packages to build from command line
        uses: actions/github-script@v5
        id: get-packages-from-command-line
        if: ${{startsWith(github.event.comment.body, '/build ')}}
        with:
          script: |
            const args = context.payload.comment.body;
            const regex = /\/build ([a-z\d\/\.\-\+ ]+)/;
            const isMatched = args.match(regex);
            if (!isMatched) throw "No packages found in the command!";
            const packages = args.split('/build ')[1].split(' ');
            return packages;

      - name: Update comment
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{steps.create-comment.outputs.comment-id}}
          body: |
            ❌ Nothing to do!

    outputs:
      matrix: ${{steps.get-packages-from-repo.outputs.result || steps.get-packages-from-command-line.outputs.result}}
      comment-id: ${{steps.create-comment.outputs.comment-id}}

  build:
    needs: get-packages
    runs-on: ubuntu-latest
    container: ghcr.io/aosc-dev/aosc-os-buildkit-daily:latest
    strategy:
      matrix:
        package: ${{fromJson(needs.get-packages.outputs.matrix)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install GitHub CLI
        if: ${{github.event.issue.pull_request}}
        env:
          GH_VERSION: 2.0.0
          GH_ARCH: amd64
        run: |
          curl -LO https://github.com/cli/cli/releases/download/v$GH_VERSION/gh_${GH_VERSION}_linux_$GH_ARCH.tar.gz
          tar -xf gh_${GH_VERSION}_linux_$GH_ARCH.tar.gz
          ln -s $GITHUB_WORKSPACE/gh_${GH_VERSION}_linux_$GH_ARCH/bin/gh /usr/bin/gh

      - name: Checkout pull request
        if: ${{github.event.issue.pull_request}}
        env:
          PR_NUMBER: ${{github.event.issue.number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr checkout $PR_NUMBER

      - name: Configure the container
        run: |
          mkdir -p /var/lib/acbs
          ln -s $GITHUB_WORKSPACE /var/lib/acbs/repo
          sed -i 's/Null Packager <null@aosc.xyz>/GitHub Actions <discussions@lists.aosc.io>/' /etc/autobuild/ab3cfg.sh
          apt-get update && yes | apt-get -yf full-upgrade && apt-get -y autoremove

      - name: Build the package
        shell: 'script -eqc "bash --noprofile --norc -eo pipefail {0}"'
        env:
          PACKAGE: ${{matrix.package}}
          CARGO_TERM_COLOR: always
        run: acbs-build "$PACKAGE"

      - name: Upload the package
        uses: actions/upload-artifact@v2
        with:
          name: debs_${{matrix.package}}
          path: /debs

      - name: Update comment when succeed
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{needs.get-packages.outputs.comment-id}}
          body: |
            ✅ Building `${{matrix.package}}` ends with status **${{job.status}}**.

      - name: Update comment when not succeed
        uses: peter-evans/create-or-update-comment@v1
        if: ${{!success()}}
        with:
          comment-id: ${{needs.get-packages.outputs.comment-id}}
          body: |
            ❌ Building `${{matrix.package}}` ends with status **${{job.status}}**.
