name: Build package on request

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build ') }}
    runs-on: ubuntu-latest
    container: aosc/aosc-os-buildkit:latest

    steps:
      # https://github.com/dotnet/runtime/blob/main/.github/workflows/backport.yml
      - name: Get the package to build
        uses: actions/github-script@v5
        id: get-package
        with:
          script: |
            const regex = /\/build ([a-z\d\/\.\-]+)/;
            package = regex.exec(context.payload.comment.body);
            if (package == null) throw "No package found in the command!";
            return package[1];
          result-encoding: string
      
      - name: Get the metadata of PR
        uses: actions/github-script@v5
        id: get-head-sha
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            })
            return {
              sha: pr.data.head.sha,
              repo: pr.data.head.repo.full_name
            }
      
      - name: Prepare for building the package
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          git clone https://github.com/${{ fromJson(steps.get-head-sha.outputs.result).repo }} .
          git checkout ${{ fromJson(steps.get-head-sha.outputs.result).sha }}
          mkdir -p /var/lib/acbs
          ln -s $PWD /var/lib/acbs/repo
          sed -i 's/Null Packager <null@aosc.xyz>/GitHub Actions <discussions@lists.aosc.io>/' /etc/autobuild/ab3cfg.sh

      - name: Build the package
        working-directory: ${{env.GITHUB_WORKSPACE}}
        env:
          PACKAGE: ${{steps.get-package.outputs.result}}
        run: script -eqc "acbs-build \"${{env.PACKAGE}}\""

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: /debs
