name: Build package on request

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{startsWith(github.event.comment.body, '/build ')}}
    runs-on: ubuntu-latest
    container: aosc/aosc-os-buildkit:latest

    steps:
      # https://github.com/dotnet/runtime/blob/main/.github/workflows/backport.yml
      - name: Get the package to build
        uses: actions/github-script@v5
        id: get-package
        with:
          script: |
            const regex = /\/build ([a-z\d\/\.\-]+)/;
            package = regex.exec(context.payload.comment.body);
            if (package == null) throw "No package found in the command!";
            return package[1];
          result-encoding: string

      - uses: actions/checkout@v2
      
      - name: Install GitHub CLI
        if: ${{github.event.issue.pull_request}}
        env:
          GH_VERSION: 2.0.0
          GH_ARCH: amd64
        run: |
          curl -LO https://github.com/cli/cli/releases/download/v${{env.GH_VERSION}}/gh_${{env.GH_VERSION}}_linux_${{env.GH_ARCH}}.tar.gz
          tar -xf gh_${{env.GH_VERSION}}_linux_${{env.GH_ARCH}}.tar.gz
          ln -s ${PWD}/gh_${{env.GH_VERSION}}_linux_${{env.GH_ARCH}}/bin/gh /usr/bin/gh

      - name: Checkout PR
        if: ${{github.event.issue.pull_request}}
        env:
          PR_NUMBER: ${{github.event.issue.number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr checkout ${{env.PR_NUMBER}}

      - name: Prepare for building the package
        run: |
          mkdir -p /var/lib/acbs
          ln -s $GITHUB_WORKSPACE /var/lib/acbs/repo
          sed -i 's/Null Packager <null@aosc.xyz>/GitHub Actions <discussions@lists.aosc.io>/' /etc/autobuild/ab3cfg.sh
          sed -i 's/https:\/\/repo.aosc.io\//https:\/\/aosc-repo.freetls.fastly.net\//' /etc/apt/sources.list
          apt-get update && yes | apt-get -yf full-upgrade && apt-get -y autoremove

      - name: Build the package
        working-directory: ${{env.GITHUB_WORKSPACE}}
        env:
          PACKAGE: ${{steps.get-package.outputs.result}}
        run: script -eqc "acbs-build \"${{env.PACKAGE}}\""

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: debs
          path: /debs
