name: Publish buildkit daily container

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tarball:
    runs-on: [self-hosted, aosc-os, x64]

    steps:
      - name: Install aoscbootstrap
        run: yes | sudo apt install -yf aoscbootstrap

      - name: Build tarball
        shell: 'script -eqc "bash --noprofile --norc -eo pipefail {0}"'
        run: sudo generate-releases buildkit

      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: os-amd64-buildkit
          path: os-amd64/buildkit

      - name: Remove artifact
        if: always()
        run: sudo rm -rf os-amd64

  docker:
    needs: tarball
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download tarball
        uses: actions/download-artifact@v2
        with:
          name: os-amd64-buildkit

      - name: Rename tarball
        run: mv aosc-os_buildkit*.tar.xz .github/workflows/aosc-os_buildkit.tar.xz

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .github/workflows
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
