name: Check LGTM label

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check lgtm label
        uses: actions/github-script@v5
        with:
          script: |
            if (${{!contains(github.event.pull_request.labels, 'lgtm')}}) throw "lgtm label not set";
